version: "3.8"
services:                     # 컨테이너 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db:
    container_name: spring-db
    image: mysql:8.0         # 사용할 이미지
    restart: always
    environment:
      - MYSQL_DATABASE=spring-db
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=root_pw
    ports:
      - "3306:3306"           # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
#    env_file:
#      - .env
#    command:
#      - --character-set-server=utf8mb4
#      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .dbdata:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
  test-app:
    build:                     # 이미지 빌드에 필요한 정보 설정
      context: ./
      dockerfile: Dockerfile
#      ports:
#        - 8080:8080
#      depends_on:              # 반드시 db컨테이너가 구동된 후에 test-app 컨테이너를 구동시키겠다
#        - db
