version: "3.8"
services: # 컨테이너 정의 ( 컴포즈에서 컨테이너 : 서비스 )
  db:
    container_name: spring-db
    image: mysql:5.7 # 사용할 이미지
    restart: always
    environment:
      - MYSQL_DATABASE=spring-db
      - MYSQL_ROOT_HOST='%'
      - MYSQL_ROOT_PASSWORD=root_pw
      - TZ=Asia/Seoul
    ports:
      - "3306:3306" # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
    env_file:
      - .env
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - .dbdata:/var/lib/mysql # -v 옵션 (다렉토리 마운트 설정)
